#
# Copyright (c) 2026 Oracle and/or its affiliates.
#
# The Universal Permissive License (UPL), Version 1.0
#
# Subject to the condition set forth below, permission is hereby granted to any
# person obtaining a copy of this software, associated documentation and/or data
# (collectively the "Software"), free of charge and under any and all copyright
# rights in the Software, and any and all patent rights owned or freely
# licensable by each licensor hereunder covering either (i) the unmodified
# Software as contributed to or provided by such licensor, or (ii) the Larger
# Works (as defined below), to deal in both
#
# (a) the Software, and
#
# (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
# one is included with the Software (each a "Larger Work" to which the Software
# is contributed by such licensors),
#
# without restriction, including without limitation the rights to copy, create
# derivative works of, display, perform, and distribute the Software and make,
# use, sell, offer for sale, import, export, have made, and have sold the
# Software and the Larger Work(s), and to sublicense the foregoing rights on
# either these or other terms.
#
# This license is subject to the following condition:
#
# The above copyright notice and either this complete permission notice or at
# a minimum a reference to the UPL must be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#---------------------------------------------
# Properties required for building Jipher
#---------------------------------------------

# Properties used for signing the JCE provider
propertyJceKsFile=
propertyJceKsAlias=
propertyJceKsStorePass=

#---------------------------------------------
# Path to the OpenSSL install base directory.
# The directory must contain the following files (if a `lib64` subdirectory exists then it will be used instead of `lib`):
# - Core library
#    `lib/libcrypto.3.dylib` or `lib/libcrypto.so.3` or `lib\libcrypto-3.dll`, as appropriate to the platform
# - FIPS module
#     `lib/ossl-modules/fips.dylib` or `lib/ossl-modules/fips.so` or `lib\ossl-modules\fips.dll`, as appropriate to the platform
# - FIPS module configuration
#     `ssl/fipsmodule.cnf` or `ssl/openssl.cnf`
# Note: This property can also be set as a system property
jipher.openssl.dir=/lib64
#jipher.openssl.dir=C:/Program Files/OpenSSL/bin

#---------------------------------------------
# Use OpenSSL native library dependencies provided by the Operating System.
jipher.openssl.useOsInstance=true

# Enforce code coverage by failing the build when JaCoCo coverage thresholds are not met.
# Set to false when testing against OpenSSL distributions that do not support features such as PQC,
# causing related tests to be skipped and measured coverage to fall below the configured thresholds.
enforceCoverage=true
